#!/bin/bash
# Displays information about subdomains.

# Check if a domain name is provided as a command-line argument
if [ $# -ne 1 ]; then
    exit 1
fi

output=$(dig "$1" | grep -A1 'ANSWER SECTION:')
subdomain=$(echo "$output" | awk '{print $1}' | cut -d'.' -f1)  # Extract only the subdomain part
record_type=$(echo "$output" | awk '{print $4}')
destination=$(echo "$output" | awk '{print $5}')

echo "The subdomain $subdomain is a $record_type record and points to $destination"

