#!/bin/env bash
# Displays information about subdomains.


subdomain_info () {
	output=$(dig "$2"."$1" | grep -A1 'ANSWER SECTION:')
	subdomain=$2
	record_type=$(echo "$output" | awk 'NR==2 {print $4}')
	destination=$(echo "$output" | awk 'NR==2 {print $5}')

	printf "The subdomain %s is a %s record and points to %s\n" "$subdomain" "$record_type" "$destination"
}

if [ "$#" -eq 1 ]
then
	subdomain_info "$1" "www"
	subdomain_info "$1" "lb-01"
	subdomain_info "$1" "web-01"
	subdomain_info "$1" "web-02"
elif [ "$#" -eq 2 ]
then
	subdomain_info "$1" "$2"
fi
