#!/usr/bin/env bash
#installs ngnix and configures it to listen on port 80 and return Hello World! when curled
sudo apt-get update
sudo apt-get install -y nginx

echo "server {
    listen 80;
    location / {
        return 200 'Hello World!';
        add_header Content-Type text/plain;
    }
    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=dQw4w9WgXcQ;
    }
    location /rr {
    	return 404 'Ceci n'est pas une page'
	add_header Content-Type text/plain;
    }
}" | sudo tee /etc/nginx/sites-available/default

sudo service nginx restart
