#!/usr/bin/env bash
# Install and configure HAproxy on your lb-01 server.

sudo apt-get update
sudo apt-get install --no-install-recommends software-properties-common -y
sudo add-apt-repository ppa:vbernat/haproxy-2.0 -y
sudo apt-get update
sudo apt-get install haproxy=2.0.\* -y

# Configure HAProxy
cat <<EOF | sudo tee /etc/haproxy/haproxy.cfg
frontend my_frontend
    bind *:80
    default_backend my_backend_servers

backend my_backend_servers
    balance roundrobin
    server 521150-web-01 18.206.233.120:80 check
    server 521150-web-02 52.91.146.216:80 check
EOF

sudo service haproxy restart
