#!/usr/bin/env bash
# Install and configure HAproxy on your lb-01 server.

sudo apt-get update
sudo apt-get install haproxy -y
sudo echo "ENABLED=1" >> /etc/default/haproxy

# Configure HAProxy
cat <<EOF | sudo tee /etc/haproxy/haproxy.cfg
frontend ahmed-codes.tech
    timeout client  30000
    bind 0:80
    default_backend ahmed-codes.tech_backend

backend ahmed-codes.tech_backend
    timeout connect  3000
    timeout server  30000
    balance roundrobin
    server 521150-web-01 18.206.233.120:80 check
    server 521150-web-02 52.91.146.216:80 check
EOF

sudo service haproxy restart
