#!/usr/bin/env bash
#manages manage_my_process

SERVICE="./manage_my_process"

start() {
	$SERVICE &
	echo "$$" > /var/run/my_process.pid
	echo "manage_my_process started"
}

# Function to stop the service
stop() {
	pkill -f "$SERVICE"
        rm /var/run/my_process.pid
        echo "manage_my_process stopped"
}

restart() {
	pkill -f "$SERVICE"
        rm /var/run/my_process.pid

	$SERVICE &
        echo "$$" > /var/run/my_process.pid

        echo "manage_my_process restarted"
}

case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    restart)
        restart
        ;;
    *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
        ;;
esac

exit 0
