#!/usr/bin/env bash
#Bash script that displays the content of the file /etc/passwd
while IFS= read -r line
do
	usr=$(echo "$line" | cut -d':' -f1)
	pswd=$(echo "$line" | cut -d':' -f2)
	uid=$(echo "$line" | cut -d':' -f3)
	gid=$(echo "$line" | cut -d':' -f4)
	info=$(echo "$line" | cut -d':' -f5)
	home=$(echo "$line" | cut -d':' -f6)
	cmd=$(echo "$line" | cut -d':' -f7)

	echo "The user $usr is part of the $gid gang, lives in $home and rides $cmd. $uid's place is protected by the passcode $pswd, more info about the user here: $info"
done < /etc/passwd
