#!/usr/bin/env bash
#Bash script that displays the visitor IP along with the HTTP status code from the Apache log file.
awk -F' ' '{count[$1]++; status[$1]=$9} END {for (ip in count) print count[ip], ip, status[ip]}' apache-access.log | sort -nrk1
