#!/usr/bin/env bash
# reloads Gunicorn in a gracefull way

guni_pids=$(pgrep gunicorn)

if [ -z "$guni_pids" ]; then
    echo "No Gunicorn processes found."
    exit 1
fi

for pid in $guni_pids; do
    kill -HUP "$pid"
    echo "Successfully reloaded Gunicorn"
done
